### ISSUE TITLE
todo For v0.2

### ISSUE THREAD

**Issue by grunklejp** [johnpaulkiser/StreamerCap#1]
- [x]  Link to streams
- [x]  Create cron jobs for twitch api job
- [x]  Create category field for for twitch
- [x]  Create feedback google form in footer 
- [x]  Create posgres db
